### ISSUE TITLE
Redstore direction bug

### ISSUE THREAD

**Issue by KAJIKK** [elmfrain/cnmcu#20]
Hello! While tinkering with your mod, I think I found a bug. The video is self-explanatory.
Mods: ModMenu, Fabric api, cnmcu, and redstone resource pack.

Code:
```
  .org $E000 ; Start of the program memory
start:
  lda #%0001
  sta $7040 ; GPIODIR0
loop:
  lda $7003 ; GPIOPV3 (Left pin)
  eor $7001
  sta $7000
  jmp loop ; Jump back to the loop
  
  .org $FFFC ; Near the end of the program memory
  .word start ; Reset vector
  .word $0000 ; Interrupt vector (not used)
```

https://github.com/elmfrain/cnmcu/assets/62884492/36f9ee01-3f5b-4ead-b17c-e46e9fc98f0b

**Comment by KAJIKK** [comment]
Github video is broken for me so just in case: https://youtu.be/8guOuj3ZtSI

**Comment by elmfrain** [comment]
Interesting, I think I might know how to resolve this issue. Thank you for video! I'll get to work on it soon
